= Playground JEE

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
This `JEE Playground` project is just a playground for JEE samples.


== Technical information
  * The release versions are based on link:http://semver.org[Semantic Versioning 2.0.0].
  * The latest release require `JavaEE 7` (or newer) and is build with link:https://maven.apache.org[Maven] (version `3.3.x`).
  * All samples are tested on link:http://www.payara.fish/[Payara JEE Server 4.1.x]


== Current Features _(for this branch)_

  * Run `ActiveMQ` samples (see `de.mirb.pg.jee.ActiveMqSample`).
    ** With embedded `ActiveMQ` broker (`vm://localhost`)
    ** with `ActiveMQ` broker via Docker (`tcp://localhost:31616`)
      *** `docker run -it --rm -p 38161:8161 -p 31616:61616 -P webcenter/activemq:latest`
      *** Admin console: http://localhost:38161 with user/pwd: admin/admin
  * Run `ActiveMQ` client via `JNDI.properties` samples (see `de.mirb.pg.jee.ActiveMqJndi`).
    ** with `ActiveMQ` broker via Docker (`tcp://localhost:31616`)
      *** `docker run -it --rm -p 38161:8161 -p 31616:61616 -P webcenter/activemq:latest`
      *** Admin console: http://localhost:38161 with user/pwd: admin/admin
  * Deploy WAR on Payara Server for `DefaultJmsService` sample
    .. Start Server
    .. To send sample content: Do GET request on http://localhost:8080/pg-jee/default/send?content=sampleContent
    .. To receive sample content: Do GET request on http://localhost:8080/pg-jee/default/receive
  * Connect to ActiveMQ (from Payara) -> http://blog.payara.fish/connecting-to-activemq-with-payara-server
  * Run with Payara -> ActiveMQ
    .. Start ActiveMQ: `docker run -it --rm -p 38161:8161 -p 31616:61616 -P webcenter/activemq:latest`
    .. `wget http://repo1.maven.org/maven2/org/apache/activemq/activemq-rar/5.14.3/activemq-rar-5.14.3.rar`
    .. `asadmin start-domain`
    .. `asadmin deploy --type rar activemq-rar-5.14.3.rar`
    .. `asadmin create-resource-adapter-config  --property ServerUrl='tcp\://localhost\:31616':UserName='admin':Password='admin' activemq-rar-5.14.3`
    .. `asadmin create-connector-connection-pool  --raname activemq-rar-5.14.3 --connectiondefinition javax.jms.ConnectionFactory --ping true --isconnectvalidatereq true jms/myConnectionPool`
    .. `asadmin create-connector-resource --poolname jms/myConnectionPool jms/myConnectionFactory`
    .. `asadmin create-admin-object --raname activemq-rar-5.14.3 --restype javax.jms.Queue --property PhysicalName=TESTQ jms/TESTQ`
    .. `asadmin create-admin-object --raname activemq-rar-5.14.3 --restype javax.jms.Topic --property PhysicalName=TESTTOPIC jms/test-topic`

== New and Noteworthy

  * *nothing*

== Roadmap

  * *none*

== Interesting Links/Blogs/Tutorial related to this playground project

  * link:https://docs.jboss.org/hornetq/2.2.5.Final/user-manual/en/html/using-jms.html[JBoss Documentation]
  * link:http://activemq.apache.org/jndi-support.html[Active MQ JNDI Support]
