= Playground JEE

== Disclaimer
Current source code and version is published without license. +
If you (somebody) want to use this in his project please contact me.
Afterwards I will grant the use of this code without warranty.
When I find some time to inform myself about the different possible licenses at link:http://choosealicense.com[choosealicense.com]
I will probably change to a suitable license.

== General information
This `JEE Playground` project is just a playground for JEE samples.


== Technical information
  * The release versions are based on link:http://semver.org[Semantic Versioning 2.0.0].
  * The latest release require `JavaEE 7` (or newer) and is build with link:https://maven.apache.org[Maven] (version `3.3.x`).


== Current Features _(for this branch)_

  * Run `ActiveMQ` samples (see `de.mirb.pg.jee.ActiveMqSample`.
    ** With embedded `ActiveMQ` broker (`vm://localhost`)
    ** with `ActiveMQ` broker via Docker (`tcp://localhost:31616`)
      *** `docker run -it --rm -p 38161:8161 -p 31616:61616 -P webcenter/activemq:latest`
      *** Admin console: http://localhost:38161 with user/pwd: admin/admin


== New and Noteworthy

  * *nothing*

== Roadmap

  * *none*
